### ISSUE TITLE
Mobilenet SSD

### ISSUE THREAD

**Issue by BurhanSabir** [nikunjmshah/Person-Tracking-and-Re-ID#1]
People_counter.py file isn't producing bounding boxes for us...
Will you please elaborate?

**Comment by nikunjmshah** [comment]
Can you please share the exact error output?

**Comment by BurhanSabir** [comment]
there is no error people_counter.py is running. but the bounding boxes aren't produced...
it returns the same video

**Comment by nikunjmshah** [comment]
I am sorry the people_counter.py code is not correctly modified for the latest repository. Please use darkness_people_counter.py if possible. If you need to use Mobilenet SSD then you can try to modify people_counter.py to make it similar to darknet_people_counter.py as in example attached. The attached example successfully works in the colab file attached in repository. Please do:
!python people_counter.py -o out.mp4
instead of:
!python darknet_people_counter.py -o out.mp4 -i videos/sample1.mp4

Please change .txt to .py

[people_counter.txt](https://github.com/nikunjmshah/Person-Tracking-and-Re-ID/files/7162446/people_counter.txt)

Output video:

https://user-images.githubusercontent.com/19552179/133269353-e8839e47-cc34-4579-a7ed-702e9badcfe0.mp4

Hope this helps.

**Comment by BurhanSabir** [comment]
thank you soo much...
Hope so this will work...
keep up the good work
